services:
  postgres:
    image: postgres:15
    container_name: fin-eventor_postgres
    environment:
      POSTGRES_DB: fin-eventor-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: fin-eventor-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: fin-eventor-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: fin-eventor-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: fin-eventor-zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://fin-eventor-kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/bin/api"]
    ports:
      - "8082:8082"
      - "44044:44044"
    depends_on:
      - postgres
      - kafka
    environment:
      CONFIG_PATH: ./configs/api/local.yaml

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/bin/worker"]
    depends_on:
      - postgres
      - kafka
    environment:
      CONFIG_PATH: ./configs/worker/local.yaml

volumes:
  pgdata:
