app:
  mode: "local"

storage:
  host: "postgres"
  user: "postgres"
  password: "postgres"
  port: 5432
  database: "fin-eventor-db"
  migration: true

grpc:
  port: 44044
  timeout: 5s
  time: 15m
  max_connection_idle: 5m
  max_connection_age: 5m

http:
  address: "localhost"
  port: "8082"
  timeout: 4s
  idle_timeout: 30s
  user: ""

kafka:
  brokers:
    - "kafka:9092"
  topic: "fin-eventor"